### ISSUE TITLE
.htaccess not added in /public after installing this with help of composer

### ISSUE THREAD

**Issue by pouyana** [symfony/apache-pack#1]
Is this pack working? According to https://github.com/symfony/demo/issues/711#issuecomment-349295057 it should add `.htaccess` to the `public` folder. 
But for me it did not do anything at all.

**Comment by jeremy-crapet** [comment]
Hi @pouyana,

I've just tried it and it works, the `.htaccess` file is added in the public directory (see https://github.com/symfony/recipes-contrib/blob/master/symfony/apache-pack/1.0/manifest.json).

Could you provide more informations if this is still an issue for you?

**Comment by dtdpro** [comment]
Using a clone of the symfony/demo app with the package manually added into composer.json, I have this issue.

On **composer install** (heroku deployment and local deployment) the .htaccess file is not added. 

However when you run **composer update** (both locations) it is added.

**Comment by jeremy-crapet** [comment]
Hi @dtdpro,

You probably have a composer.lock file that composer uses to install all the packages (see [here](https://getcomposer.org/doc/03-cli.md#install)) and that's why it doesn't read the composer.json file to add this package but when you do a `composer update` it works.

**Comment by karousn** [comment]
i have the same problem after installing this recipes

**Comment by 1151879477** [comment]
Is it a Windows issue? Why is it not directly contained in the installation package?

**Comment by 1151879477** [comment]
The vendor\symfony\ apach-pack directory has only one composer. Json?No other files?

**Comment by karousn** [comment]
@meiyoufengzhengdexian : it calling  [this repo](https://github.com/symfony/recipes-contrib/blob/master/symfony/apache-pack/1.0/manifest.json)

**Comment by gsylvestre** [comment]
Same issue here, after a fresh install with symfony/skeleton, on Windows. 
.htaccess file is not created in public/ directory. 
No error shown when installing apache-pack with `composer req apache-pack`

**Comment by ehymel** [comment]
For another data point, not working for me either (symfony 4), even after 'composer update'.

**Comment by karousn** [comment]
i thought may be it be a good feature to have the possibility to execute the "flex script" another time since it failed to do what we want without make change if there file in the path.

**Comment by Invis1ble** [comment]
`composer update` also does not write any `.htaccess` file in `public` dir

**Comment by Gerben321** [comment]
Same on Windows

**Comment by kamilmaliszewski** [comment]
The same for me.  I have SF4 & MacOS. File .htaccess is not created after composer install or update. I have installed SF from 'symfony/website-skeleton'

**Comment by fabpot** [comment]
Anyone willing to debug the issue and propose a patch?

**Comment by gsylvestre** [comment]
Issue seems to be fixed for me with https://github.com/symfony/flex/commit/b72fcd4167eba4eea211d82dd511a5ff288df7dd

No problems after updating symfony/flex to >= 1.0.62

This is my understanding of the issue: the `Console\Input\ArgvInput` was set to _non-interactive_, leading the confirmation question (whether to execute the contrib recipe or not) to be skipped, thus using default value of 'n'.

**Comment by fabpot** [comment]
@gsylvestre Thanks for the investigation. Upgrading Flex from time to time is a good idea :) Closing as this is now fixed.

**Comment by haroldmodesto** [comment]
Not working for me. I have symfony/flex 1.0.71

**Comment by rwslinkman** [comment]
I'm also not seeing a `.htaccess` file being put in the `public` dir.
Using `symfony/flex v1.0.78`.

**Comment by rwslinkman** [comment]
I was able to resolve the issue in my case.
When inspecting my `composer.json` file, I saw that the `symfony/apache-pack` dependency was in the `require` section. 

I removed that line and ran `composer update` and composer removed the package.
Then I executed `composer require apache-pack --dev` and chose the `a` options when asked.
Afterwards I looked at my git status and saw the `.htaccess` file in the `public` directory.
Refreshing the web page showed the debug toolbar at the bottom of the page.

Hope this helps anyone.

**Comment by tonybob-tl** [comment]
A few things. Make sure when you list the files under the folder, you request the hidden files as well (e.g., _ls -a_). It could be there, you are just not seeing it... Also, if you are getting errors during the downloads, make sure you have enough memory, especially if you are doing this on a remote server via SSH or similar. Also, errors may occur if your environment isn't set correctly, (e.g., _export APP_ENV=prod_ if you are building a production environment - check by _echo $APP_ENV_).

**Comment by StanleySathler** [comment]
I faced the same issue.

What I did was slightly different from what @rwslinkman suggested. Since I was deploying my app into Heroku, I couldn't have `symfony/apache-pack` as a dev dependency.

First, I removed my already existent installation. I just removed the `symfony/apache-pack` dependency from my `composer.json` file (manually) and then I ran `$ compose update` to update my `composer.lock` file. After that, my `composer.lock` file didn't have `apache-pack` anymore.

So, I just ran the installation command again: `$ compose require symfony/apache-pack`. This time, a few options were given confirming if I wanted to execute the recipe. I just chose option _[a] Yes for all packages, only for the current installation session_.

This time, both `compose.json` and `compose.lock` had the `symfony/apache-pack` dependency, but it had also the `.htaccess` file in the `/public` directory.

**Comment by webdevilopers** [comment]
I had a similar problem when executing the composer update via PHPStorm console. The interaction menu @StanleySathler mentions did not appear. I then used my Ubuntu terminal which worked fine.

**Comment by vigorousss** [comment]
how resolve this problem?

**Comment by StanleySathler** [comment]
@vigorousss did you try all the different steps explained above?

Specially these ones:
https://github.com/symfony/apache-pack/issues/1#issuecomment-377782559
https://github.com/symfony/apache-pack/issues/1#issuecomment-443883907

**Comment by ghost** [comment]
I fixed this by clearing cache.

```
composer remove symfony/apache-pack
composer clearcache
composer require symfony/apache-pack
```

**Comment by makhloufi-lounis** [comment]
> J'ai pu résoudre le problème dans mon cas.
> Lors de l'inspection de mon `composer.json`dossier, j'ai vu que la `symfony/apache-pack`dépendance était dans la `require`section.
> 
> J'ai supprimé cette ligne et exécuté `composer update`et le compositeur a supprimé le paquet.
> Ensuite, j'ai exécuté `composer require apache-pack --dev`et j'ai choisi les `a`options quand on leur a demandé.
> Ensuite, j'ai regardé mon statut git et vu le `.htaccess`fichier dans le `public`répertoire.
> L'actualisation de la page Web a montré la barre d'outils de débogage en bas de la page.
> 
> J'espère que cela aide n'importe qui.

>Thanks it worked for me too,  just a remark no need for --dev
