### ISSUE TITLE
htaccess syntax error

### ISSUE THREAD

**Issue by ysabro** [symfony/apache-pack#8]
Hello,

On Symfony 4.4, i used the bundle **symfony/apache-pack**  (composer require symfony/apache-pack), as indicated on [Symfony web site](https://symfony.com/doc/4.4/setup/web_server_configuration.html) to generate rewrite rules.

The pack install a .htaccess file into public directory. (/public)

My web server Apache 2.4, shows that the line 55 has errors: "RewriteRule: bad flag delimiters"

`RewriteRule ^ %{ENV:BASE}/index.php [L]Directory`

The word "Directory" at the end of the line is the problem.

Could you please fix it, the correct line is:

`RewriteRule ^ %{ENV:BASE}/index.php [L]`

Thank you!

Yasser.

**Comment by Tobion** [comment]
There is no such "Directory" at the end of this line, see https://github.com/symfony/recipes-contrib/blob/master/symfony/apache-pack/1.0/public/.htaccess
So it must come by accident from somewhere else.
Ticket can be closed.
